#!/bin/sh


send_notification() {
# Use brillo to logarithmically adjust laptop screen brightness
# and send a notification displaying the current brightness level after.
#	brightness=$(printf "%.0f\n" "$(brillo -Gq)")


# Use brightnessctl to adjust laptop screen brightness non-logarithmically
# and send a notfication displaying the current brightness level after.
	brightness=$((( $(brightnessctl get) * 100) / 255))


	dunstify -a "changebrightness" -u low -r 9993 -h int:value:"$brightness" -i "brightness" "Brightness" "Currently at $brightness%" -t 2000
	 
	
}

case $1 in
up)
	brightnessctl -s set +5%
	send_notification "$1"
	;;
down)
	brightnessctl -s set 5%-
	send_notification "$1"
	;;
esac
